### ISSUE TITLE
Who robbed us? 💰

### ISSUE THREAD

**Issue by chrisman** [chrisman/skookums-and-dragons#35]
Somebody stole Kiriel's 100 gold and 10,000 Nubs's notes! Now Kiriel has given Nubs one week to return the money or he'll put a hit out on him!

**Balance**
To be forgiven now that Kiriel and the Gang are working together to prevent outright war

- 50 gold

### Todo
**Plan A: Direct Confrontation**
- [x] Talk to Ballard at Enrique's
- [x] Get Plunk from the Huntsman
- [x] Investigate the Westside Wayside mercs at the Broken Shield
- [x] Investigate Dariel and the Shadows
- [x] Move Dariel's hot item
- [ ] Sell Dariel out

**Plan B: Rig da Fite**
- [ ] Trick Gronk into throwing a fight
- [ ] Get Valdra in on the deal

**Plan C: Heist!**
- [ ] Robbing the vault

### Clues
- Kiriel and Elgren were going to use the money to get Mud Tree and the Orphans out of Wayside and to the Green Isles in order to prevent an escalation of hostility and a possible outright war. Ostensibly, somebody trying to prevent this from happening would be trying to bring about that war.
- The thieves seemed to be two elven couriers with no qualms about using magic quasi-publically
- Eckhart and Elsidore are two half-elves who kind of fit the description but Eckhart is kinda slow.
- Ballard says the Westside Wayside are runners who kind of play fast and loose with the no magic rules
- The witch hunters were out almost immediately
- Kiriel got a funny face when Sully mentioned Gronk
- The gang told the Death Mark Watchman a little bit about the shadowrunners.
- Loriel from the Broken Shield tips us off to the existence Shadows, the eastside shadowrunners
