### ISSUE TITLE
The Exile

### ISSUE THREAD

**Issue by chrisman** [chrisman/skookums-and-dragons#36]
A dwarven Exile smuggled a bunch of magic children away from the Order

## Todo
- [x] Who issued this hit? **The Order**
- [x] Who is the target? **The Exile**
- [x] Why do they want them dead? **For betraying the order and stealing the children**
- [x] Why did the Watchers accept the contract? **Because they are the enforcement arm of the Order**
- [x] Investigate Elgren's journal.
- [x] Ask TEB about Watchers Mark
- [x] Find the exile? **Rescued Mud Tree from the Embassy**
- [x] Get to Kiriel and ask for help getting out of town
- [ ] Go southwest and spring the kids from the Dwarphanage
- [ ] Go to Volkstadt (in the Convocation) and get a boat.
- [ ] get everybody to the Green Isles

## Notes
- Working with Kiriel and Elgren
    - Kiriel's stacks of money were to finance Mud Tree's escape and voyage?
    - Elgren was going secure a ship and help him skip town?
- Related to Dwarven Exile hit mark Dash stole
    - Dash stole the mark from the Watchman
    - It's a big 1 pip contract
    - There is a seal on the front (the target), it is the Dwarven Mark of Exile, but you don't recognize the individual
- Investigate Elgren's journal
    - Druidic code: Exile. Smuggle. Children.
    - Thieves Cant: Dwarf. Orphan. Green Isle. Safety. Urgent.
- TEB definitely recognizes the mark of exile
    - "anybody trying to collect the mark is in grave danger."
    - "A heretic turned his back on the Order"
    - "You know about the children then"
    - The Exile took the children (witches and wizards) right out of their grasp. They believe he's in the South. Was supposed to destroy a town. Dwarves caught him and they exiled him from the Iron Society.
