### ISSUE TITLE
Who is this hit mark for? ☠️

### ISSUE THREAD

**Issue by chrisman** [chrisman/skookums-and-dragons#37]
Somebody put a hit out on somebody else.

**Todo**:
- [ ] Who issued this hit?
- [ ] Who is the target?
- [ ] Why do they want them dead?
- [ ] Why did the Watchers accept the contract?

**Notes**:
- Dash stole the mark from the Watchman
- It's a big 1 pip contract
- There is a seal on the front (the target), but you don't recognize it.
- There is no issuer on the back.
- Its base is the Dwarven Mark of Exile

**Comment by chrisman** [comment]
merge into #36
